config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"  
  }

  devise_scope :user do
  get "/welcome", to: "users/sessions#new"
  get "/users/edit", to: "users/registrations#edit"
  get "/users/sign_out", to: "users/sessions#destroy"
end

resources :home

resources :books do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
  resources :reviews do
  member do 
    get :like
    get :unlike
  end
end
  resources :authors
end

resources :communities do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end

resources :posts do
  member do
    get :like
    get :unlike
  end
  resources :comments do
  member do 
    get :like
    get :unlike
  end
end
end

resources :users do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end
resources :translations

root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, through: :reviews
    has_many :reviews
    belongs_to :community
    has_and_belongs_to_many :authors
	acts_as_followable

    has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    validates :title, :description, :ISBN, :community_id, presence: true
    validates :title, :ISBN, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	acts_as_likeable
	validates :body, presence: true
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :books
	acts_as_followable
	
	has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :body, presence: true
	acts_as_likeable
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
	validates :body, presence: true
	acts_as_likeable
end

app/models/translation.rb
class Translation < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :books, through: :reviews
  has_many :reviews
  has_and_belongs_to_many :communities
  acts_as_follower
  acts_as_followable
  acts_as_liker

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "40x40>" }, :default_url => "missing.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment, only: [:like, :unlike]

	def like
		current_user.like!(@comment)
		find_comment_likes
		respond_to do |format|
			if current_user.likes?(@comment)
				format.html {redirect_to root_path }
				format.js { render action: 'like'} 
			end
		end
	end

	def unlike
		current_user.unlike!(@comment)
		find_comment_likes
		respond_to do |format|
			unless current_user.likes?(@comment)
				format.html {redirect_to root_path }
				format.js { render action: 'unlike'} 
			end
		end
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:body))
		@comment.user_id = current_user.id if current_user
		find_post_likes
		respond_to do |format|
			if @comment.save
				format.html {redirect_to root_path }
				format.js {}
			else
				render 'new'
			end
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to root_path
	end

	private

	def find_comment
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def find_comment_likes
		@likes = Like.where("likeable_type = 'Comment' AND likeable_id = #{@comment.id}").count
	end

	def find_post_likes
		@likes = Like.where("likeable_type = 'Post' AND likeable_id = #{@post.id}").count
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :signed_in, only: [:index]
	before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

	  def index	
		@posts = Post.where("user_id IN (?)",@followees_ids).order("created_at DESC")

		@reviews = Review.where("user_id IN (?)",@followees_ids).order("created_at DESC")
		@book_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"Book").order("created_at DESC").limit(3)
		@user_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"User").order("created_at DESC").limit(3)
		@activity = (@book_follow + @user_follow).sort{|a,b| a.created_at <=> b.created_at}
		@last_follow = @activity.last
		@last_review = @reviews.first
	  end

	  protected

	def find_user
		@user = User.find(current_user.id)
		find_followees
	end

	def find_followees
		@followees = Follow.where("follower_id = #{current_user.id} AND followable_type = 'User'")
		@followees_ids = @followees.pluck(:followable_id)
		@followees_ids << current_user.id
	end

	def signed_in
		unless user_signed_in?
	  		redirect_to '/welcome'
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do%>

<div class="row">
     <div class="col-md-1">
          <%= image_tag User.find(comment.user_id).image.url , size: "30x30", class: 'img-c' %>
     </div>
     <div class="col-md-6">
         <strong><%=link_to "#{[User.find(comment.user_id).first_name,User.find(comment.user_id).last_name].join(" ")}", user_path(comment.user_id) %></strong>
         <div class="comment-likes">
         <% likes = Like.where("likeable_type = 'Comment' AND likeable_id = #{comment.id}").count%>
         <p><%= pluralize(likes, "like")%></p>
         </div>
         <p><%= comment.body%></p>
                     
    </div>
     <div class="btn-group btn-group-xs">
            <div class="comment-like">
                   <% if current_user.likes?(comment) %>                               
                   <h4><%=link_to "unlike", unlike_post_comment_path(comment.post_id,comment), remote: true,  class: 'btn btn-default' %></h4>
                   <% else %>
                   <h4><%=link_to "like", like_post_comment_path(comment.post_id,comment), remote: true,  class: 'btn btn-default'%></h4>
                   <% end %>
            </div>
     </div>
</div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#post_<%= @comment.post_id %> * .comments').append(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();
$("#post_<%= @post.id %> * .comment-info").html('<p><%= pluralize(@likes, "like")%>, <%= pluralize(@post.comments.count, "Comment") %> </p>');

app/views/comments/like.js.erb
$("#comment_<%= @comment.id %> * .comment-likes").html('<p><%= pluralize(@likes, "like")%> </p>');
$("#comment_<%= @comment.id %> * .comment-like").html('<h4><%=link_to "unlike", unlike_post_comment_path(@comment.post_id,@comment),remote: true,  class: "btn btn-default" %></h4>');

app/views/comments/unlike.js.erb
$("#comment_<%= @comment.id %> * .comment-likes").html('<p><%= pluralize(@likes, "like")%> </p>');
$("#comment_<%= @comment.id %> * .comment-like").html('<h4><%=link_to "like", like_post_comment_path(@comment.post_id,@comment),remote: true,  class: "btn btn-default" %></h4>');