config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"  
  }

  devise_scope :user do
  get "/welcome", to: "users/sessions#new"
  get "/users/edit", to: "users/registrations#edit"
  get "/users/sign_out", to: "users/sessions#destroy"
end

resources :home

resources :books do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
  resources :reviews do
  member do 
    get :like
    get :unlike
  end
end
  resources :authors
end

resources :communities do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end

resources :posts do
  member do
    get :like
    get :unlike
  end
  resources :comments do
  member do 
    get :like
    get :unlike
  end
end
end

resources :users do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end
resources :translations

root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :books, through: :reviews
  has_many :reviews
  has_and_belongs_to_many :communities
  acts_as_follower
  acts_as_followable
  acts_as_liker

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "40x40>" }, :default_url => "missing.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

   def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     "/users/edit"
   end

   def after_update_path_for(resource)
      communities_path
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:follow, :unfollow, :followers, :show, :edit, :update, :destroy]
	before_action :authenticate_user!
	
	def follow
		current_user.follow!(@user)
		if current_user.follows?(@user)
			redirect_to @user
		else
			render 'index'
		end
	end

	def unfollow
		current_user.unfollow!(@user)
		redirect_to @user
	end

	def show
		dob = @user.birthday
		age(dob)

		@posts = Post.where("user_id = #{@user.id}").order("created_at DESC")
		@book_follow = Follow.where("follower_id = #{@user.id} AND followable_type= 'Book'").order("created_at DESC").limit(3)
		@user_follow = Follow.where("follower_id = #{@user.id} AND followable_type= 'User'").order("created_at DESC").limit(3)
		@reviews = Review.where("user_id = #{@user.id}").order("created_at DESC").limit(3)
		@activity = (@book_follow + @user_follow).sort{|a,b| a.created_at <=> b.created_at}
		@activity.reverse!
	end

	protected

	def find_user
		@user = User.find(params[:id])
		@followees = @user.followees(User)
		@followers = @user.followers(User)
		@followers_count = @user.followers(User).count
	end

	def age(dob)
		now = Time.now.to_date
		@age = now.year - dob.year
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user-style', media: 'all', 'data-turbolinks-track' => true %>

        <div class="row">
            <div class="col-md-12">
                <a href="#" class="logo1">BookShare</a>
            </div>
        </div>
</div>

 <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                         <li><%=link_to "Profile", user_path(current_user) %></li>
                         <li><%=link_to "edit Account", edit_user_registration_path(@user) %></li>
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <li ><a href="#">About</a></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
        </div>
<div class="container">
            <div class="row">
                <div class="content">
                <div class="col-lg-8">
                    <div class="userinfo">
                        <div class="row">
                            <div class="col-lg-2">
                                <%= image_tag @user.image.url , size: "100x100" %>
                            </div>
                            <div class="col-lg-6">
                                <h4><%=[@user.first_name,@user.last_name].join(" ")%> (<%= @user.username%>)</h4>
                                <% unless current_user == @user %>
                                    <% if current_user.follows?(@user) %>
                                          <h4><%=link_to "unfollow", unfollow_user_path(@user)%></h4>
                                    <% else %>
                                          <h4><%=link_to "follow", follow_user_path(@user)%></h4>
                                    <% end %>
                                <% end %>
                                <h4><%= @user.gender%></h4>
                                <h4><%= @age.to_s + " years old"%></h4>
                                <h4>Country: <%= @user.country%></h4>
                                <h4>Total Reviews: <%=@reviews.count%></h4>
                                <h4>Total followers: <%= @followers_count%></h4>
                            </div>
                        </div>
                        </div>
                        <div class="row">
                            <h3>Latest Activity</h3>
                            <hr>
                            <h4>
                          
                                <% @activity.each do |b|%>
                                <p><%=@user.first_name%> followed a <%= b.followable_type%>:
                                    <% if b.followable_type == 'Book'%>
                                <%= link_to "#{Book.find(b.followable_id).title}", book_path(Book.find(b.followable_id))%> <%= time_ago_in_words(b.created_at)%> Ago</p>
                                    <% else %>
                                  <%=link_to "#{[User.find(b.followable_id).first_name,User.find(b.followable_id).last_name].join(" ")}", user_path(b.followable_id)%> <%= time_ago_in_words(b.created_at)%> Ago</p>
                                    <% end %>
                                <% end %>
                             
                            </h4>
                            
                             <h4>
                             
                                <% @reviews.each do |b|%>
                                <p><%=@user.first_name%> gave <%= pluralize(b.rating, "stars")%> to <%= link_to "#{Book.find(b.book_id).title}", book_path(Book.find(b.book_id))%> and wrote a <%= link_to "review", book_path(Book.find(b.book_id), anchor: "review_#{b.id}") %> <%= time_ago_in_words(b.created_at)%> Ago
                                    </p>
                                <% end %>
                              
                            </h4>
                           
                        </div>

                </div>
                
                
                <div class="col-lg-4">
                    <div class="friends">
                    <div class="row">
                        <div class="col-lg-4"><h3>Following</h3>
                        <hr>
                            </div>
                    </div>

                    <% @followees.each do |followees| %>
                     <div class="row"> 
                        <div class="col-lg-2">   
                            <%= image_tag followees.image.url(:thumb), size: "40x40" %>
                        </div>
                        <div class="col-lg-5">
                            <h5><%= link_to [followees.first_name,followees.last_name].join(" "), followees%></h5> 
                        </div>
                         
                        <div class="col-lg-5">
                            <div class="btn-group btn-group-x4">
                            <% unless current_user == followees %>
                            <% if current_user.follows?(followees) %>
                                <%= link_to "unfollow",unfollow_user_path(followees), class: 'btn btn-default' %>
                              <% else %>
                                <%= link_to "follow",follow_user_path(followees), class: 'btn btn-default' %>
                            <% end %>
                            <% end %>
                            </div>
                        </div>
                    </div>
                    <% end %>
                    <br>
                </div>
                </div>
                 
            </div>

       </div>
    </div>