config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"  
  }

  devise_scope :user do
  get "/welcome", to: "users/sessions#new"
  get "/users/edit", to: "users/registrations#edit"
  get "/users/sign_out", to: "users/sessions#destroy"
end

resources :home

resources :books do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
  resources :reviews do
  member do 
    get :like
    get :unlike
  end
end
  resources :authors
end

resources :communities do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end

resources :posts do
  member do
    get :like
    get :unlike
  end
  resources :comments do
  member do 
    get :like
    get :unlike
  end
end
end

resources :users do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end
resources :translations

root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, through: :reviews
    has_many :reviews
    belongs_to :community
    has_and_belongs_to_many :authors
	acts_as_followable

    has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    validates :title, :description, :ISBN, :community_id, presence: true
    validates :title, :ISBN, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	acts_as_likeable
	validates :body, presence: true
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :books
	acts_as_followable
	
	has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :body, presence: true
	acts_as_likeable
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
	validates :body, presence: true
	acts_as_likeable
end

app/models/translation.rb
class Translation < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :books, through: :reviews
  has_many :reviews
  has_and_belongs_to_many :communities
  acts_as_follower
  acts_as_followable
  acts_as_liker

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "40x40>" }, :default_url => "missing.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:follow, :unfollow, :followers, :show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new]

	def follow
		current_user.follow!(@book)

		respond_to do |format|
			if current_user.follows?(@book)
				format.html {redirect_to book_path(@book) }
				format.js { render action: 'follow'} 
			end
	 	end
	end

	def unfollow
		current_user.unfollow!(@book)
		respond_to do |format|
			format.html {redirect_to book_path(@book) }
			format.js { render action: 'unfollow'} 
		end
	end



	def new
		@book = current_user.books.build
	end

	def show
		@authors = @book.authors.map{ |author| [author.first_name,author.last_name].join(" ") }.join(",")

		@reviews = Review.where(book_id: @book.id).order("created_at DESC")
		if @reviews.blank?
		    @avg_review = 0
		else
		    @avg_review = @reviews.average(:rating).round(2)
    	end
	end

	def create
		@book = current_user.books.build(book_params)
		if @book.save
			redirect_to new_book_author_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to new_book_author_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to posts_path
	end

	private

	def find_book
		@book = Book.find(params[:id])
		@followers = @book.followers(User).count
	end

	def book_params
		params.require(:book).permit(:title, :description,:ISBN, :community_id, :image)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :signed_in, only: [:index]
	before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

	  def index	
		@posts = Post.where("user_id IN (?)",@followees_ids).order("created_at DESC")

		@reviews = Review.where("user_id IN (?)",@followees_ids).order("created_at DESC")
		@book_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"Book").order("created_at DESC").limit(3)
		@user_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"User").order("created_at DESC").limit(3)
		@activity = (@book_follow + @user_follow).sort{|a,b| a.created_at <=> b.created_at}
		@last_follow = @activity.last
		@last_review = @reviews.first
	  end

	  protected

	def find_user
		@user = User.find(current_user.id)
		find_followees
	end

	def find_followees
		@followees = Follow.where("follower_id = #{current_user.id} AND followable_type = 'User'")
		@followees_ids = @followees.pluck(:followable_id)
		@followees_ids << current_user.id
	end

	def signed_in
		unless user_signed_in?
	  		redirect_to '/welcome'
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= stylesheet_link_tag 'register', media: 'all', 'data-turbolinks-track' => true %>

     <div class="jumbotron">
    <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                        <li><%=link_to "Profile", user_path(current_user) %></li>
          
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <% end %>
                        <li ><a href="#">About</a></li>
                    </ul>
                </div>
            </nav>


            <div class="col-md-8 col-md-offset-2">
  <%= form_for @book, html: {class: "form-horizontal signup-form", :multipart => true} do |f| %>

    <div class="form-group">
      <%= f.label :title, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :ISBN, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :ISBN, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :community_id, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
     <%= f.select :community_id, options_for_select(Community.all.map { |community| [community.name, community.id] }) , {}, class: 'form-control'  %>

    </div>
    </div>
 
     <div class="form-group ">
     <div class="col-md-5 col-xs-8 col-md-offset-2">
        <%= f.label :image %>
        <%= f.file_field :image %>             
     </div>
     <div class="col-md-3 col-xs-4">
        <%= f.submit "Add Book", class: 'form-control btn btn-primary' %>
    </div>
    </div>
 
<% end %>

app/views/books/follow.js.erb
$("#follow_<%=@book.id%>").html('<h4><%=link_to "unfollow", unfollow_book_path(@book), remote:true, class: "btn"%></h4>');

app/views/books/new.html.erb
<%= stylesheet_link_tag 'register', media: 'all', 'data-turbolinks-track' => true %>

     <div class="jumbotron">
    <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                         <li><%=link_to "Profile", user_path(current_user) %></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <li ><a href="#">About</a></li>
                        <% end %>
                    </ul>
                </div>
            </nav>


            <div class="col-md-8 col-md-offset-2">
  <%= form_for @book, html: {class: "form-horizontal signup-form", :multipart => true} do |f| %>

    <div class="form-group">
      <%= f.label :title, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :ISBN, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :ISBN, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group">
      <%= f.label :community_id, class: 'col-md-2 control-label' %>
    <div class="col-md-8">
     <%= f.select :community_id, options_for_select(Community.all.map { |community| [community.name, community.id] }) , {}, class: 'form-control'  %>

    </div>
    </div>
 
     <div class="form-group ">
     <div class="col-md-5 col-xs-8 col-md-offset-2">
        <%= f.label :image %>
        <%= f.file_field :image %>             
     </div>
     <div class="col-md-3 col-xs-4">
        <%= f.submit "Add Book", class: 'form-control btn btn-primary' %>
    </div>
    </div>
 
<% end %>

app/views/books/show.html.erb
<%= stylesheet_link_tag 'bookstyle', media: 'all', 'data-turbolinks-track' => false %>
<%= javascript_include_tag 'jquery.raty.js'%>
<div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="#" class="logo1">BookShare</a>
            </div>
        </div>
</div>

 <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                         <li><%=link_to "Profile", user_path(current_user) %></li>
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <li ><a href="#">About</a></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
        </div>
 <div class="container">
            <div class="Book-info">
            <div class="updateBook col-md-offset-10">
            <% if user_signed_in?%>
              <h4><%=link_to "update this book", edit_book_path(@book) %></h4>
              <% end %>
            </div>
        <div class="row">
            <div class="col-lg-2">
               <%= image_tag @book.image.url(:medium) %>
                     <div id="follow_<%=@book.id%>">
                     <% if user_signed_in?%>
                     <% if current_user.follows?(@book) %>
                         <h4><%= link_to "unfollow", unfollow_book_path(@book), class: 'btn'%></h4>
                     <% else %>
                         <h4><%= link_to "follow", follow_book_path(@book), class: 'btn'%></h4>
                     <% end %>
                     <% end %>
                </div>
        </div>
                
                <div class="col-lg-10">
                    <div class="info">
                       
                    <h3><%=@book.title%></h3>
                     <h5>by <%=@authors%> </h5>
                     <p>(<%= pluralize(@followers, "follower") %>)</p>
                        <p><%= @book.description%></p>
                           
                        
                    <div class="rate text-center">
                      <div class="rate">
                      <div class="star-rating" data-score=<%= @avg_review%>></div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            </div>
    
            
<!--    reviews -->
    <div class="reviews">
        <div class="container">
        <div class="row">
            <h2>Reviews</h2>
            <% if user_signed_in?%>
            <% if current_user.follows?(@book)%>
                  <div class="row reviewinput">
                <div class="col-md-12">
                    <%= form_for([@book,Review.new] , remote: true, html:{ class: 'form-horizontal post'}) do |form|%>
                      <div class="form-group">
                    <div class="col-md-7 col-md-offset-1">
                     <%= form.text_field :body, class: 'form-control textinput' %>
                     <div id="star-rating"></div>
                      </div>
                      <div class="col-md-3">
                      <%= form.submit "Add Review", class: 'form-control' %>  
                      </div>
                  </div>
                  <% end %>
                  <% end %>
                </div>
        </div>
        <% end %> 
            
        </div>
            <hr>
        </div>
    </div>
    
<!--   end reviews -->
    
<!--user review-->
    
    <div class="container">
    <div class="review-body">
        <%= render @book.reviews.reverse %>
          <hr>
        
    </div>
    </div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/books/unfollow.js.erb
$("#follow_<%=@book.id%>").html('<h4><%=link_to "follow", follow_book_path(@book), remote:true, class: "btn"%></h4>');