config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"  
  }

  devise_scope :user do
  get "/welcome", to: "users/sessions#new"
  get "/users/edit", to: "users/registrations#edit"
  get "/users/sign_out", to: "users/sessions#destroy"
end

resources :home

resources :books do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
  resources :reviews do
  member do 
    get :like
    get :unlike
  end
end
  resources :authors
end

resources :communities do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end

resources :posts do
  member do
    get :like
    get :unlike
  end
  resources :comments do
  member do 
    get :like
    get :unlike
  end
end
end

resources :users do 
  member do
    get :follow
    get :unfollow
    get :followers
  end
end
resources :translations

root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, through: :reviews
    has_many :reviews
    belongs_to :community
    has_and_belongs_to_many :authors
	acts_as_followable

    has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    validates :title, :description, :ISBN, :community_id, presence: true
    validates :title, :ISBN, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	acts_as_likeable
	validates :body, presence: true
end

app/models/community.rb
class Community < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :books
	acts_as_followable
	
	has_attached_file :image, :styles => { :medium => "177x249", :thumb => "100x100" }, :default_url => "book.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :body, presence: true
	acts_as_likeable
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
	validates :body, presence: true
	acts_as_likeable
end

app/models/translation.rb
class Translation < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :books, through: :reviews
  has_many :reviews
  has_and_belongs_to_many :communities
  acts_as_follower
  acts_as_followable
  acts_as_liker

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "40x40>" }, :default_url => "missing.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
	before_action :find_community, only: [:follow, :unfollow, :followers, :show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new]

	def follow
		current_user.follow!(@community)
		respond_to do |format|
			if current_user.follows?(@community)
				format.html {redirect_to root_path }
				format.js { render action: 'follow'} 
			end
	 	end
	end

	def unfollow
		current_user.unfollow!(@community)
		respond_to do |format|
			format.html {redirect_to root_path }
			format.js { render action: 'unfollow'} 
		end
	end

	def followers
		@followers = @community.followers(User)
	end

	def index
		@communities = Community.all
	end

	def show
		@books = Book.where("community_id = #{@community.id}").order("created_at DESC")
	end

	def new
		@community = Community.new
	end

	def create
		@community.new(community_params)
		if @community.save
			redirect_to @community
		else
			render 'new'
		end
	end


	def update
		if @community.update(params[:community].permit(:title,:description))
			redirect_to @community
		else
			render 'edit'
		end
	end

	def destroy
		@community.destroy

		redirect_to communities_path
	end


	protected

	def find_community
		@community = Community.find(params[:id])
		@followers = @community.followers(User).count
	end

	def community_params
		params.require(:community).permit(:title,:description)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :signed_in, only: [:index]
	before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

	  def index	
		@posts = Post.where("user_id IN (?)",@followees_ids).order("created_at DESC")

		@reviews = Review.where("user_id IN (?)",@followees_ids).order("created_at DESC")
		@book_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"Book").order("created_at DESC").limit(3)
		@user_follow = Follow.where("follower_id IN (?) AND followable_type = ?",@followees_ids,"User").order("created_at DESC").limit(3)
		@activity = (@book_follow + @user_follow).sort{|a,b| a.created_at <=> b.created_at}
		@last_follow = @activity.last
		@last_review = @reviews.first
	  end

	  protected

	def find_user
		@user = User.find(current_user.id)
		find_followees
	end

	def find_followees
		@followees = Follow.where("follower_id = #{current_user.id} AND followable_type = 'User'")
		@followees_ids = @followees.pluck(:followable_id)
		@followees_ids << current_user.id
	end

	def signed_in
		unless user_signed_in?
	  		redirect_to '/welcome'
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_community.html.erb
<%= div_for community do %>
        <strong><%= link_to "#{community.name}", community_path(community) %></strong>
             <p><%= community.description %></p>
                 <div class="btn-group btn-group-xs">
                     <div class="follow-community">
                     <% if user_signed_in?%>
          				 <% if current_user.follows?(community) %>
                               <h4><%=link_to "unfollow", unfollow_community_path(community), remote: true, class: 'btn btn-primary'%></h4>
                         <% else %>
                               <h4><%=link_to "follow", follow_community_path(community), remote: true, class: 'btn btn-primary'%></h4>
                         <% end %>
                         <% end %>
                     </div>
                </div>
<% end %>

app/views/communities/follow.js.erb
$("#community_<%= @community.id %> * .follow-community").html('<h4><%=link_to "unfollow", unfollow_community_path(@community), remote: true, class: "btn btn-primary"%></h4>');

app/views/communities/index.html.erb
<%= stylesheet_link_tag 'community-style', media: 'all' %>
<div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="#" class="logo1"></a>
            </div>
        </div>
</div>

<div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                        <li><%=link_to "Profile", user_path(current_user) %></li>
                      
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <li ><a href="#">About</a></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
            <div class="col-md-6 col-md-offset-3">
            <h3>Follow communities to get updates</h3>
            <div class="addbook">
            <% if user_signed_in?%>
            <%= link_to "Add Book", new_book_path, class: 'btn btn-primary col-md-offset-2' %>
            <%= link_to "next", home_index_path, class: 'btn btn-primary col-md-offset-3' %>
            <% end %>
            </div>
            </div>
            

            <div class="row">
            <% @communities.each do |community| %>
                <div class="comm">
            <div class="col-md-6">
                <%= render community %>
            </div>
                </div>
        <% end %> 

</div>

</div>

app/views/communities/show.html.erb
<%= stylesheet_link_tag 'bookstyle', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'jquery.raty.js'%>
<div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="#" class="logo1">BookShare</a>
            </div>
        </div>
</div>

 <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <%= link_to "Home", root_path, class: "navbar-brand"%></li>
                    </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path%></li>
                        <li><%=link_to "Communities", communities_path %></li>
                        <% if user_signed_in?%>
                       <li><%=link_to "Profile", user_path(current_user) %></li>
                         <li><%=link_to "Sign Out", users_sign_out_path%></li>
                          <% else %>
                        <li ><a href="#">Contact Us</a></li>
                        <li ><a href="#">About</a></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
        </div>
 <div class="container">
            <div class="Book-info">
        		<div class="row">
            	<div class="col-lg-2">
                <%= image_tag @community.image.url(:medium) %>
                    <div id="community_<%=@community.id%>">
                    <% if user_signed_in?%>
                     <% if current_user.follows?(@community) %>
                         <h4><%= link_to "unfollow", unfollow_community_path(@community),remote: true, class: 'btn'%></h4>
                     <% else %>
                         <h4><%= link_to "follow", follow_community_path(@community), remote: true, class: 'btn'%></h4>
                     <% end %>
                     <% end %>
                    </div>
        		</div>
                
                <div class="col-lg-10">
                    <div class="info">
                       
                    <h3><%=@community.name%></h3>
                        <p>(<%= pluralize(@followers, "User") %> follow this community)</p>
                        <p><%= @community.description%></p>
                  
                </div>
            </div>
        </div>
    </div>
    <div class="reviews">
        <div class="container">
        <div class="row">
            <h2>Books</h2>
            
        </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="container">
        <% @books.each do |book| %>
        <div class="col-md-3 col-sm-12 col-xs-12">
        	<%= image_tag book.image.url(:medium)%>
            <h5><%= link_to "#{book.title}", book_path(book)%></h5>
        	<div id="follow_<%=book.id%>">
            <% if user_signed_in?%>
            <% if current_user.follows?(book) %>
                         <h4><%= link_to "unfollow", unfollow_book_path(book),remote: true, class: 'btn'%></h4>
                     <% else %>
                         <h4><%= link_to "follow", follow_book_path(book), remote: true, class: 'btn'%></h4>
            <% end %>
            <% end %>
            </div>
        
        </div>
        <% end %>
        </div>
    </div>

</div>

app/views/communities/unfollow.js.erb
$("#community_<%= @community.id %> * .follow-community").html('<h4><%=link_to "follow", follow_community_path(@community), remote: true, class: "btn btn-primary"%></h4>');